#pragma config(Sensor, in2,    encoder,        sensorAnalog)
#pragma config(Motor,  port1,           depositor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          collector,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void deposit(){

		clearTimer (T1);
		while (time1(T1)< 500){
			motor[collector] = 127;
		}
		motor[collector] = 0;
		clearTimer(T2);
		while(time1(T2)<5000){

			motor[depositor] = -20;
	}
	motor[depositor] = 0;
}

task main()
{

	deposit();


}
